language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6
    - pypy
    - pypy3
matrix:
    include:
        - python: "3.7"
          dist: xenial
          sudo: true
install:
    - travis_retry pip install .
    - travis_retry pip install zope.testing
script:
    - python setup.py test -q
notifications:
    email: false
